#!/bin/bash
filesgrep=$(ls /home/sftp/files/anime/ | grep $1)
hdd2grep=$(ls /home/sftp/mount/hdd2/anime/ | grep $1)
linenumber=$(echo -e "$filesgrep $hdd2grep" | wc -l)
if [ "$hdd2grep" == '' ] && [ "$filesgrep" == '' ]; then
	echo "No files found"
	exit 0
else
	continue
fi

if [ $linenumber != 1 ]; then
	echo "There were $linenumber files found"
	n=1
	if [ $linenumber -le 5 ]; then
		echo -n "The found files are: "
		while [ $n -le $linenumber ]
		do
			line=$(echo "$filesgrep $hdd2grep" | sed -n "$n"p)
			if [ "$n" -lt "$linenumber" ];
			 then
				echo -n "$line, ";
			 else
				echo "$line."
			fi
			n=`expr $n + 1`;
		done
	else
		echo "That's way too many to display nicely. Please refine your search terms."
	fi
else
	echo "There was one file found."
	n=1
	echo -n "The found file was: "
	line=$(echo "$filesgrep $hdd2grep" | sed -n "$n"p)
	echo "$line."	
fi
