#!/bin/bash
channel=$@
source configuration
source functions
touch "$ircdir/$server/$channel/out"
joined=true
tailf -n1 "$ircdir/$server/$channel/out" |\
 while read -r date time nick msg; do
	set -- $msg
	start=$1
	shift
	rest=$@
	truenick=$(echo $nick | sed -e "s/^<//" -e "s/>$//")

	joined=$(tail -n1 "in/$channel")
	if [ "$joined" == "false" ]; then
		exit 0
	fi
	if [ "$(echo $channel | head -c 1)" == '#' ]; then
		if [[ "$msg" == swissboxbot:* ]]; then
			./scripts/saymyname $channel $truenick $msg
		fi
	elif [ "$truenick" == "$channel" ]; then
		./script/saymyname $channel $truenick $msg
	else
		msgowner $channel and $truenick are giving me issues!
		echo "/p $channel :\"I broke!\"" >> "$ircdir/$server/in"
		exit 0
	fi
done
