#!/bin/bash
echo "--commandme executing with $@" >&3
channel=$@
source runningconf.cnf
source functions
echo > "$ircdir/$server/$channel/out"
joined=true
echo "true" > "in/$channel"
tailf -n1 "$ircdir/$server/$channel/out" |\
 while read -r date time nick msg; do
	echo "the line is $date $time $nick $msg" >&3
	echo "Read on $channel worked (maybe)" >&3
	tail -n1 "$ircdir/$server/$channel/out" >&3
	set -- $msg
	start=$1
	shift
	rest=$@
	truenick=${nick:1:-1}
	joined=$(tail -n1 "in/$channel")
	if [ "$joined" == "false" ]; then
		exit 0
	fi
	if [ -z "$date" ]; then
		echo "Waiting" >&3
	elif [ "$(echo $channel | head -c 1)" == '#' ]; then
		if [[ "$msg" == swissboxbot:* ]]; then
			./scripts/saymyname $channel $truenick $msg
			echo "$date $time $nick $msg" >&4
		fi
	elif [ "$truenick" == "$channel" ]; then
		echo "In a privmsg, was messaged $msg from $nick" >&3
		./scripts/saymyname $channel $truenick $msg 
	else
		msgowner $channel and $truenick are giving me issues!
		echo "$channel and $truenick and $msg caused errors in commandme, but we'll try to continue" >&2
		echo "the line is $date $time $nick $msg" >&3
		#exit 1
	fi
done
