#!/usr/bin/env bash
#iibot/core
##Seperating this in order to make logging possibly possible. This seems like a really stupid way to do it though...
##I also need to figure out how to kill the bot when it's running like this.

#ctrl-c inttrupt
function control_c() {
	echo -e "quitting\n"
	rm -r $ircdir/$server/*
	mkdir $ircdir/$server/$owner/
	touch $ircdir/$server/$owner/out
	iipid=$(cat iipid.txt)
	kill -9 "$iipid"
	run=false
	exit 0
	}

#command grabbing

function ownermessage(){
	tailf -n1 "$ircdir/$server/$owner/out" | while read -r date time nick msg; do
		$iidir/ownercommand $msg
	done 
}


function startii(){
##Initial Cleanup
rm -r "$ircdir/$server/"
mkdir -p "$ircdir/$server/$owner/"
touch "$ircdir/$server/$owner/out"
source runningconf.cnf
source ./functions
source ./extrafunc
while true; do 
	echo "ii starting up!" >&1
	$iidir/ii -s $server -n $nick -f "Iamabot" -i $ircdir &
	iipid="$!"
	export iipid
	echo "The PID for ii is $iipid" >&3
	echo $iipid > iipid.txt
	sleep 3
	##you'll have to put your own command to identify with nickserv here, you can't have my pass
	for i in $initchannel; do
		echo "joining $i" >&3
		echo "/j $i" > "$ircdir/$server/in"
		sleep 1
		commandme $i &
	done
	msgowner "I AM READY"
	ownermessage &
	./register
	wait "$iipid"
	echo "ii seems to have crashed, should be restarting now!" >&2
done 
}


trap control_c SIGINT
