#!/bin/bash

##Setting the debug level
##Because of who knows what, I can't do this with a for string. Looks like I have to manually set it.
if [[ $debuglevel -ge 2 ]]; then
	if [[ $debuglevel -ge 3 ]]; then
		if [[ $debuglevel -ge 4 ]]; then
			if [[ $debuglevel -ge 5 ]]; then
				exec 2>&1 3>&1 4>&1 5>&1
			else
				exec 2>&1 3>&1 4>&1 5>/dev/null
			fi
		else
			exec 2>&1 3>&1 4>/dev/null 5>/dev/null
		fi
	else
		exec 2>&1 3>/dev/null 4>/dev/null 5>/dev/null
	fi
else
	exec 2>/dev/null 3>/dev/null 4>/dev/null 5>/dev/null
fi
for i in `seq 1 5`; do
	echo this is a $i level message >&$i
done
