#!/bin/bash
ircdir=$1
owner=$2
server=$3
iidir=$4
function commandme(){
	touch "$ircdir/$server/$channel/out"
	tailf -n1 "$ircdir/$server/$channel/out" | while read -r date time nick msg; do 
	echo $nick $msg
	if [ "$(echo $msg | head -c 1)" == '!' ]; then
		$iidir/commandme $msg > "$ircdir/$server/$channel/in"
	fi
done
}
tailf -n1 "$ircdir/$server/$owner/out" | while read -r date time nick msg; do
	set -- $msg
	i=$1
	shift
	channel=$1
	shift
	message=$@
	echo "Master wants me to $i $channel and $message"
	if [ "$(echo $channel | head -c 1)" != "#" ]; then
		echo $channel
		newchannel=$(echo "#""$channel")
		channel="$newchannel"
		echo $newchannel
	fi


	#Join
	if [ "$i" == 'j' ] || [ "$i" == 'join' ]; then
		if [ ! -d "$ircdir/$server/$channel/" ]; then
			echo "/j $channel"
			echo "/j $channel" > "$ircdir/$server/in"
			echo "/privmsg $owner :Joining $channel" > "$ircdir/$server/in"
			commandme &
		else
			echo "/j $channel"
			echo "/j $channel" > "$ircdir/$server/in"
			echo "/privmsg $owner :Joining $channel" > "$ircdir/$server/in"
		fi	
	#Speak
	elif [ "$i" == 'say' ] || [ "$i" == 'Say' ]; then
		echo "/privmsg $channel :$message"
		echo "/privmsg $channel :$message" > "$ircdir/$server/in"

	#Part
	elif [ "$i" == 'q' ] || [ "$i" == 'part' ] || [ "$i" == 'p' ]; then
		echo "$msg"
		msgowner Parting $channel with message $message
		echo "/part $channel :$message" > "$ircdir/$server/in"

#	#Quit  -- not yet functional
#	elif [ "$i" == 'quit' ] || [ "$i" == 'Quit' ]; then
#		echo "quit"
#		msgowner Shutting Down
#		control_c
	fi

done  

