#!/bin/bash
#######################################################
#
# A Script to modify access lists for iibot by Swiss
#
# Just basically checks the person who asked, if it's
# the owner, then continue, otherwise, screwit
#
#
#
#
#
#
#
#
# swiss <swiss@veryoblvio.us>
#######################################################
set -- $@
channel=$1
shift
truenick=$1
shift
command=$1
shift
rest=$@
. runningconf.cnf
. functions
if [ "$truenick" == "$owner" ]; then
	if [ "$command" == 'allow' ]; then
		echo $rest >> ./allow/$channel
		msgowner "allowing $rest on $channel"
	elif [ "$command" == 'deny' ]; then
		sed -ie "s/$rest//g" ./allow/$channel
		msgowner "allow/$channel contains:"
		msgowner "$(cat ./allow/$channel)"
	fi
fi	
