#!/bin/bash
#######################################################
#
# A Script to modify access lists for iibot by Swiss
#
# Just basically checks the person who asked, if it's
# the owner, then continue, otherwise, screwit
#
#
#
#
#
#
#
#
# swiss <swiss@veryoblvio.us>
#######################################################
if [ "$truenick" == "$owner" ]; then
	if [ "$subcommand" == 'allow' ]; then
		echo $subquery >> ./allow/$channel
		msgowner "allowing $subquery on $channel"
	elif [ "$subcommand" == 'deny' ]; then
		sed -ie "s/$subquery//g" ./allow/$channel
		msgowner "allow/$channel contains:"
		msgowner "$(cat ./allow/$channel)"
	fi
fi	
