#!/bin/bash
set -- $@
channel=$1
shift
truenick=$1
shift
command=$1
shift
rest=$@
. runningconf.cnf
. functions
if [ "$truenick" == "$owner" ]; then
	if [ "$command" == 'allow' ]; then
		echo $rest >> ./allow/$channel
		msgowner "allowing $rest on $channel"
	elif [ "$command" == 'deny' ]; then
		sed -ie "s/$rest//g" ./allow/$channel
		msgowner "allow/$channel contains:"
		msgowner "$(cat ./allow/$channel)"
	fi
fi	
