#!/bin/bash
if [ "$truenick" == "$owner" ]; then
	if [ "$subcommand" == "list" ]; then
		cat ./private/bannedwords | while read line; do
			msgowner $line;
		done
	elif [ "$subcommand" == "add" ]; then
		echo $subquery >> ./private/bannedwords
		msgowner Added $subquery
	elif [ "$subcommand" == 'remove' ]; then
		sed -ie "s/$subquery//g" ./private/bannedwords
		msgowner removed $subquery
	else
		msgowner "The only commands I know are add remove and list!"
	fi		
else
	echo "You don't get to do that $truenick!"
fi
