#!/bin/bash
set -- $@
channel=$1
shift
truenick=$1
shift
commandold=$1
entire=$@
shift
rest=$@
command=${commandold,,}


function allowcheck() {
echo "Allowcheck on $swissbox by $truenick" >3&
if [ "${channel:0:1}" == '#' ];then
	allowed=$(cat "./allow/$channel")
else 
	allowed=$(cat "./allow/priv")
fi
if [[ "$allowed" != *$@* ]]; then
	echo "This functionality is disabled for $channel"
	exit 0
fi
}
##specialized commands for the privmsgs. Not needed yet.
#if [ "$truenick" == "$channel" ]; then
#
#fi

##IDEA
#ownercheck function, to check if current nick is the owner, easier to do than if statements.



#lets start with help
if [ "$command" == 'help' ]; then
	./scripts/help $truenick ${rest,,}
##main search ( swissbox
elif [ "$command" == 'search' ]; then 
	allowcheck swissbox
	./scripts/search $rest 
elif [ "$command" == 'manga' ] ; then
	allowcheck swissbox
	./scripts/manga $rest
elif [ "$command" == 'lastchap' ] ; then
	allowcheck swissbox
	./scripts/lastchap $rest
#latest modified
elif [ "$command" == 'latest' ]; then 
	allowcheck swissbox
	./scripts/latest ${rest,,}
##lets try a request system
elif [ "$command" == 'request' ] ; then
	allowcheck swissbox
	./scripts/request $truenick $rest
##Time to check space left
elif [ "$command" == 'space' ]; then 
	allowcheck swissbox
	./scripts/space $rest
##Lets check release groups!
elif [ "$command" == 'show' ]; then 
	allowcheck swissbox
	./scripts/show $rest
##Time to start having fun
elif [ "$command" == 'say' ] || [ "$command" == 'Say' ]; then
	./scripts/say $truenick $rest

elif [ "$command" == 'time' ]; then
	echo "The correct time is `date`"

##googling. Incredibly annoying, disabled by default.
elif [ "$command" == 'google' ]; then
	allowcheck google
	./scripts/google $truenick $rest
elif [ "$command" == 'bannedwords' ]; then
	./scripts/banword $truenick $rest

#need to allow swissbox and googling when needed
elif [ "$command" == 'allow' ] || [ "$command" == 'deny' ] ; then
	./scripts/allow $channel $truenick $command $rest

elif [ "$command" == 'query' ]; then
	./scripts/privlisten $truenick $msg
else
	echo "Command not recognized. Try !help?"
	echo "$truenick used incorrect command of $command with $rest" >3&
fi
