#!/bin/bash
set -- $@
channel=$1
shift
truenick=$1
shift
commandold=$1
entire=$@
shift
rest=$@
allowed=$(cat "./allow/$channel")
command=$(echo $commandold | tr [:upper:] [:lower:])
restlower=$(echo $rest | tr [:upper:] [:lower:])


function allowcheck() {
if [[ "$allowed" != *$@* ]]; then
	echo "This functionality is disabled on $channel"
	exit 0
fi
}


##main search ( swissbox
if [ "$command" == 'search' ]; then 
	allowcheck swissbox
	./scripts/search $rest > "results.txt"
	cat results.txt
elif [ "$command" == 'manga' ] ; then
	allowcheck swissbox
	./scripts/manga $rest > "results.txt"
	cat results.txt
elif [ "$command" == 'lastchap' ] ; then
	allowcheck swissbox
	./scripts/lastchap $rest
#latest modified
elif [ "$command" == 'latest' ]; then 
	allowcheck swissbox
	./scripts/latest $restlower
##lets try a request system
elif [ "$command" == 'request' ] ; then
	allowcheck swissbox
	./scripts/request $truenick $rest
##Time to check space left
elif [ "$command" == 'space' ]; then 
	allowcheck swissbox
	./scripts/space $rest
##Lets check release groups!
elif [ "$command" == 'show' ]; then 
	allowcheck swissbox
	./scripts/show $rest
##Time to start having fun
elif [ "$command" == 'say' ] || [ "$command" == 'Say' ]; then
	./scripts/say $truenick $rest
elif [ "$command" == 'time' ]; then
	echo "The correct time is `date`"

##googling. Incredibly annoying, disabled by default.
elif [ "$command" == 'google' ]; then
	allowcheck google
	./scripts/google $truenick $rest
elif [ "$command" == 'bannedwords' ]; then
	./scripts/banword $truenick $rest

#need to allow swissbox and googling when needed
elif [ "$command" == 'allow' ] || [ "$command" == 'deny' ] ; then
	./scripts/allow $channel $truenick $command $rest
fi
