#!/bin/bash
echo "GOOGLE RECIEVED" >&4
if [ "$(cat times/googletimeout)" == "true" ]; then
	echo "Please wait before continuing with searches"
	exit0
fi
if [ "$query" == "" ]; then
	echo "Please enter a term to search"
	exit 0
fi
echo "scripts/google: rest checked and timeout finished, it was $rest, and the query was $query" >&4
grep -i "$query" private/bannedwords && echo "No thanks, I don't think $owner likes the FBI"  && exit 0
curl -s --get --data-urlencode "q=$query" http://ajax.googleapis.com/ajax/services/search/web?v=1.0 > results/googleresults.txt
webaddr=$(sed 's/"unescapedUrl":"\([^"]*\).*/\1/;s/.*GwebSearch",//' < results/googleresults.txt)
title=$( sed -e 's/"titleNoFormatting":"\([^"]*\).*/\1/;s/.*",//' < results/googleresults.txt)
if [[ "$title" == *403}$ ]]; then
	echo "Sorry, looks like google has me in Time Out!"
	./scripts/timeout googletimeout &
	exit 0
else
	echo -e "The first result of your search is: \n 5,3 $title \n $webaddr" 
fi
