#!/bin/bash
echo "LASTCHAP RECIEVED" >&4
if [[ "$query" == */* ]] ; then
	echo "Why don't you try and exploit someone else?"
	exit 0
fi
echo "$subcommand is subcommand, $subquery is subquery, $query is query, $command is command, $fullcommand is full command" >&4
if [ "${subcommand,,}" == 'hentai' ]; then
	resulting=$(ls $filesdir/manga/Hentai/ | grep -i "$subquery")
	echo "scripts/lastchap: searched for $subquery in Ecchi and got $resulting" >&3
	[ -z "$resulting" ] && echo "Didn't find it in the first one, trying the first word" >&3 &&  resulting=$(ls $filesdir/manga/Hentai | grep -i "${subquery%% *}")
	if [ -n "$resulting"  ]; then
		echo "The latest chapter we have is: $(ls "$filesdir/manga/Hentai/$resulting" | tail -n 1)"
	else
		echo "Whoops, I couldn't find $subquery in Hentai. Why don't you try a standard search?"
	fi
elif [ "${subcommand,,}" == 'ecchi' ]; then
	resulting=$(ls $filesdir/manga/Ecchi/ | grep -i "$subquery")
	echo "scripts/lastchap: searched for $subquery in Ecchi and got $resulting" >&3
	[ -z "$resulting" ] && echo "Didn't find it in the first one, trying the first word" >&3 &&  resulting=$(ls $filesdir/manga/Ecchi | grep -i "${subquery%% *}")
	if [ -n "$resulting"  ]; then
		echo "The latest chapter we have is: $(ls "$filesdir/manga/Ecchi/$resulting" | tail -n 1)"
	else
		echo "Whoops, I couldn't find $subquery in Ecchi. Why don't you try a standard search?"
	fi
else
	resulting=$(ls $filesdir/manga/Series/ | grep -i "$query")
	echo "scripts/lastchap: searched for $subquery and got $resulting" >&3
	if [ -n "$resulting" ] && [ -d "$filesdir/manga/Series/$resulting" ]
	then
		echo "The latest chapter we have is: $(ls "$filesdir/manga/Series/$resulting" | tail -n 1)"
	else
		echo "Whoops, I couldn't find $query"
	fi
fi	
