#!/bin/bash
. functions
. configuration
if [ "$(echo $1| tr [:upper:] [:lower:])" == 'ecchi' ]; then
	set -- $@
	shift
	manga=$@
	ls /home/sftp/mount/hdd2/manga/Ecchi/ | grep -i "$manga" > searchresults.txt
	echo "Searching Ecchi...."
else
	manga=$@
	ls /home/sftp/mount/hdd2/manga/ | grep -i "$manga" > searchrestults.txt
fi
##Removed filesgrep and hotswap as I have migrated to the 3tb drive
linenumber=$( wc -l < searchresults.txt)
if [ "$linenumber" == '0' ]; then
	echo "No files found"
	exit 0
fi

if [ $linenumber != 1 ]; then
	echo "There were $linenumber files found"
	if [ $linenumber -le 5 ]; then
		searchresults
	else
		echo "That's way too many to display nicely. Please refine your search terms."
	fi
else
	searchresults
fi
