#!/bin/bash
truenick=$1
type=${subquery%% *}
file=${subquery##* }
if [ "$type" != 'anime' ] && [ "$type" != 'manga*' ]; then
	privmsg $truenick "I'm sorry, i only have an anime or manga list"
	echo "$subcommand was the sub command, $query was the query. $type is the type" >&3
	exit 0
fi

if [ "$subcommand" == 'add' ]; then 
	search=$(grep -i "$file" ./request/$type)
	if [ "$search" != "" ] ; then
		privmsg $truenick "Sorry, this item has already been requested!"
	else
		echo "$truenick:	$file" >> "./request/$type"
		echo "$truenick: Your request for $file has been added!"
	fi
elif [ "$subcommand" == 'search' ]; then 
	search=$(grep -i "$file" ./request/$type)
	if [ "$search" != "" ] ; then
		grep -i "$file" ./request/$type | while read line; do
			reqnick=$(echo $line | sed -e 's/:.*$//')
			show=$(echo $line | sed -e 's/^.*://')
		echo "$show is requested by $reqnick"
		done
	else
		echo "This item doesn't seem to be in the list!"
	fi
elif [ "$subcommand" == 'list' ]; then
	cat "./request/$type" | while read line; do
		privmsg $truenick "$line"
	done
elif [ "$subcommand" == 'remove' ]; then 
	removal=$(grep -i "$file" ./request/$type)
	if [ "$removal" == "" ]; then
		privmsg $truenick "I can't find that on the list!"
	else
		reqnick=$(echo $removal | sed -e 's/:.*$//')
		if [[ "$reqnick" == *"$file"* ]]; then
			privmsg $truenick "Are you really trying to remove all of $reqnick's requests? I can't let you do that"
			exit 0
		else
			sed -ie "s/$removal//" "./request/$type"
			privmsg $truenick "Removed $removal"
			show=$(echo $removal | sed -e 's/*.*://')
			privmsg '#swissbox' "$truenick has removed $show! Sounds likes $reqnick's request got fulfilled!"
		fi
	fi
elif [ "$subcommand" == 'show' ]; then
	grep $file "./request/$type" | while read line; do
		privmsg $truenick "$line"
	done
else 
	echo "The commands are add, remove, show, or list"
fi
