#!/bin/bash
msg=$@
set -- $msg
channel=$1
shift
truenick=$1
shift
rest=${@#swissboxbot:}
words=$(echo $rest | tr [:upper:] [:lower:])
if [ "${words:0:1}" == '!' ]; then
	command=${rest:1}
	./scripts/command $channel $truenick $command
	echo "./scripts/command $channel $truenick $command" >&3
elif [ "$channel" != "$truenick" ]; then
	if [[ "$rest" == *RAGE* ]] ; then
		echo "RAAAAAAAAAAAAAAAAAAAAGE"
	fi
	if [ "$truenick" == "$owner" ]; then
		if [[ "$words" == fuck\ you* ]]; then
			echo "I-i-is that really how you feel?!?! Please don't leave me!"
		elif [[ "$words" == i\ love\ you* ]]; then
			echo "Take me away my master!"
		fi
	else
		if [ "$words" == "hello" ]; then
			echo "hi!"
		elif [[ "$words" == fuck\ you* ]]; then
			echo "Well, FUCK YOU TOO!"
		elif [[ "$words" == i\ love\ you ]]; then
			echo "I'm sorry, but I'm saving myself for $owner"
		fi
	fi
fi
