#!/bin/bash
echo "SAYMYNAME RECIEVED" >&3
echo "$rest is rest $truenick is truenick $channel is channel and $command is command" >&4
rest=${rest#swissboxbot: }
echo "$rest is the new rest" >&4
words=${rest,,}
echo "$words are the new words" >&4
echo "${words:0:1} is words:0:1" >&4
if [ "${words:0:1}" == '!' ]; then
	export fullcommand=${rest:1}
	echo "$fullcommand is the new command" >&4
	./scripts/command
	echo "sent to command!" >&4
elif [ "$channel" != "$truenick" ]; then
	if [[ "$rest" == *RAGE* ]] ; then
		echo "RAAAAAAAAAAAAAAAAAAAAGE"
	fi
	if [ "$truenick" == "$owner" ]; then
		if [[ "$words" == fuck\ you* ]]; then
			echo "I-i-is that really how you feel?!?! Please don't leave me!"
		elif [[ "$words" == i\ love\ you* ]]; then
			echo "Take me away my master!"
		fi
	else
		if [ "$words" == "hello" ]; then
			echo "hi!"
		elif [[ "$words" == fuck\ you* ]]; then
			echo "Well, FUCK YOU TOO!"
		elif [[ "$words" == i\ love\ you ]]; then
			echo "I'm sorry, but I'm saving myself for $owner"
		fi
	fi
fi
