#!/usr/bin/env bash
#############################################################
# Written By Swiss for iiBot
# Searches the system, Returns results
#
#
# swiss <swiss@veryoblivio.us>
#############################################################
ls $filesdir/anime/ | grep -i "query" > results/searchresults.txt
linenumber=$(wc -l < results/searchresults.txt)
if [ "$linenumber" == '0' ]; then
	echo "No files found"
	exit 0
elif [ "$linenumber" != 1 ]; then
	if [ $linenumber -le 5 ]; then
		results=$(searchresults self )
	else
		results="That's way too many to display nicely. Please refine your search terms."
	fi
	echo "There were $linenumber files found: $results"
else
	echo -e "There was one file found. Its is: $(searchresults self)"
fi
