#!/bin/bash
##Fixing the fact that it's named unintuitively
if [ "$query" == 'hdd1' ]; then
		rest="/dev/sdb4"
fi
	
if df -h | grep $query; then 
	set -- $(df -h | grep $query)
	filesystem=$1
	size=$2
	availible=$4
	used=$5
	mount=$6
	echo "On $mount there is $availible availible of $size. $used of this drive is full."
else
	echo "Seems this device cannot be found."
fi
